package base_constant

import (
	"github.com/coming-chat/intra-swap-core/base_entities"
	"github.com/daoleno/uniswap-sdk-core/entities"
)

var UsdGasTokensByChain = map[base_entities.ChainId][]*entities.Token{
	MAINNET:      {DAI_MAINNET, USDC_MAINNET, USDT_MAINNET},
	RINKEBY:      {DAI_RINKEBY_1, DAI_RINKEBY_2},
	ARBITRUM_ONE: {DAI_ARBITRUM, USDC_ARBITRUM, USDT_ARBITRUM},
	OPTIMISM:     {DAI_OPTIMISM, USDC_OPTIMISM, USDT_OPTIMISM},
	OPTIMISTIC_KOVAN: {
		DAI_OPTIMISTIC_KOVAN,
		USDC_OPTIMISTIC_KOVAN,
		USDT_OPTIMISTIC_KOVAN,
	},
	ARBITRUM_RINKEBY: {DAI_ARBITRUM_RINKEBY, USDT_ARBITRUM_RINKEBY},
	KOVAN:            {DAI_KOVAN, USDC_KOVAN, USDT_KOVAN},
	GÖRLI:            {DAI_GÖRLI, USDC_GÖRLI, USDT_GÖRLI, WBTC_GÖRLI},
	ROPSTEN:          {DAI_ROPSTEN, USDC_ROPSTEN, USDT_ROPSTEN},
	POLYGON:          {USDC_POLYGON},
	POLYGON_MUMBAI:   {DAI_POLYGON_MUMBAI},
	BASE:             {USDC_BASE_MAINNET},
}
